name: 'CI - Pull Request'

on:
  pull_request:

jobs:
  generate-matrix:
    name: 'Generate Matrix'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Matrix
        id: generate
        uses: zchryr/manifest@main
        with:
          manifest: 'package.json'
          ignore_dirs: 'libs,testing/logs,testing/6/sub-6'

  use-matrix:
    name: 'Test: ${{ matrix.job.relativePath }}'
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        job: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ matrix.job.cd }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Test
        run: |
          pwd
          ls -al
          echo "Insert whatever you want here :D"
