name: 'CI - Pull Request'

on:
  pull_request:
  workflow_dispatch: # Manual trigger.

jobs:
  generate-matrix:
    name: 'Generate Matrix'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Matrix
        id: generate
        uses: zchryr/manifest@main
        with:
          manifest: 'package.json'
          ignore_dirs: 'libs,testing/logs,testing/6/sub-6'

  use-matrix:
    name: 'Check Matrix'
    runs-on: ubuntu-latest
    needs: generate-matrix

    steps:
      - name: Clone
        uses: actions/checkout@v4

      # - name: Test
      #   run: |
      #     echo "${{ toJson(needs.generate-matrix.outputs.matrix) }}"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Or any other version you prefer

      - name: Compare JSONs
        run: |
          echo "FILE_JSON_STRING=$(cat .github/ci/valid.json)" >> $GITHUB_ENV

          echo "file"
          echo $FILE_JSON_STRING
          echo "\n\n\n"

          echo "env"
          echo $ENV_JSON_STRING
        # python .github/ci/compare-jsons.py
        env:
          ENV_JSON_STRING: ${{ needs.generate-matrix.outputs.matrix }} # Assuming
