name: 'CI - Pull Request'

on:
  pull_request:
  workflow_dispatch: # Manual trigger.

jobs:
  generate-matrix:
    name: 'Generate Matrix'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Matrix
        id: generate
        uses: zchryr/manifest@main
        with:
          manifest: 'package.json'
          ignore_dirs: 'libs,testing/logs,testing/6/sub-6'

  use-matrix:
    name: 'Check Matrix'
    runs-on: ubuntu-latest
    needs: generate-matrix

    steps:
      # - name: Test
      #   run: |
      #     echo "${{ toJson(needs.generate-matrix.outputs.matrix) }}"

      - name: Compare JSONs
        run: |
          # Read JSON from file
          # FILE_JSON_STRING=$(cat path/to/your/file.json)

          # Get JSON from environment variable
          ENV_JSON_STRING="${{ needs.generate-matrix.outputs.matrix }}"

          # Use Node.js to parse and compare
          node -e "
            const fileJson = JSON.parse('$FILE_JSON_STRING');
            const envJson = JSON.parse('$ENV_JSON_STRING');
            console.log(JSON.stringify(envJson));

            # if (JSON.stringify(fileJson) !== JSON.stringify(envJson)) {
            #   console.error('JSONs are not the same!');
            #   process.exit(1);
            # } else {
            #   console.log('JSONs match!');
            # }
          "
