name: 'CI - Pull Request'

on:
  pull_request:
  workflow_dispatch: # Manual trigger.

jobs:
  generate-matrix:
    name: 'Generate Matrix'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Matrix
        id: generate
        uses: zchryr/manifest@main
        with:
          manifest: 'package.json'
          ignore_dirs: 'libs,testing/logs,testing/6/sub-6'

  use-matrix:
    name: 'Check Matrix'
    runs-on: ubuntu-latest
    needs: generate-matrix

    steps:
      - name: Test
        run: |
          echo ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
          echo ${{ needs.generate-matrix.outputs.matrix }}
