name: 'CI - Pull Request'

on:
  pull_request:
  workflow_dispatch: # Manual trigger.

jobs:
  generate-matrix:
    name: 'Generate Matrix'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Matrix
        id: generate
        uses: zchryr/manifest@main
        with:
          manifest: 'package.json'
          ignore_dirs: 'libs,testing/logs,testing/6/sub-6'

  use-matrix:
    name: 'Check Matrix'
    runs-on: ubuntu-latest
    needs: generate-matrix

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Create file from matrix
        run: |
          echo "${{ needs.generate-matrix.outputs.matrix }}" > matrix.out

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install fs

      - name: Compare JSONs
        run: |
          node .github/ci/compare.js matrix.out .github/ci/valid.json
