name: 'example'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-matrix:
    name: 'Generate Matrix'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Matrix
        id: generate
        uses: zchryr/manifest@main
        with:
          manifest: 'package.json'

  use-matrix:
    name: 'Test: ${{ matrix.job.short }}'
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        job: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ matrix.job.change }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Test
        run: |
          pwd
          echo "Insert whatever you want here :D"
